"""Input parsers for ingress resources."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path


def _read_json_payload(raw: str) -> dict:
    payload = json.loads(raw)
    if not isinstance(payload, dict):
        msg = "Expected top-level JSON object"
        raise ValueError(msg)
    return payload


def load_ingresses_from_file(path: str) -> dict:
    """Load Kubernetes ingress JSON from a file generated by kubectl."""

    raw = Path(path).read_text(encoding="utf-8")
    return _read_json_payload(raw)


def load_ingresses_from_live_cluster(context: str | None = None) -> dict:
    """Load Kubernetes ingress JSON directly from a live cluster using kubectl."""

    cmd = ["kubectl", "get", "ingress", "-A", "-o", "json"]
    if context:
        cmd.extend(["--context", context])

    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        msg = f"kubectl command failed: {proc.stderr.strip() or proc.stdout.strip()}"
        raise RuntimeError(msg)
    return _read_json_payload(proc.stdout)
